# Generated by Django 5.1 on 2024-09-16 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedido",
            options={
                "ordering": ["id"],
                "verbose_name": "pedido",
                "verbose_name_plural": "pedidos",
            },
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id",
            new_name="pedido",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id",
            new_name="producto",
        ),
    ]
