# Generated by Django 5.1 on 2024-09-06 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("servicios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sevicio",
            new_name="Servicio",
        ),
    ]
