# Generated by Django 5.1 on 2024-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servicios", "0002_rename_sevicio_servicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicio",
            name="imagen",
            field=models.ImageField(upload_to="servicios"),
        ),
    ]
