# Generated by Django 5.1 on 2024-09-14 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tienda", "0002_producto_created_producto_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "producto", "verbose_name_plural": "productos"},
        ),
    ]
